// Single source of truth for the public site's security headers.
// Used by the postbuild CSP step (meta tag, out/_headers, render.yaml sync), the local preview server and tests.

/** CSP directives. Scripts: same-origin files plus the SHA-256 hashes of Next's inline bootstrap scripts. */
export function cspDirectives(scriptHashes = []) {
  return {
    'default-src': ["'self'"],
    'script-src': ["'self'", ...scriptHashes],
    // framer-motion and the DOM label layer position elements with inline styles.
    'style-src': ["'self'", "'unsafe-inline'"],
    'img-src': ["'self'", 'data:', 'blob:'],
    'font-src': ["'self'", 'data:'],
    'media-src': ["'self'"],
    'connect-src': ["'self'"],
    'worker-src': ["'self'", 'blob:'],
    'frame-src': ["'none'"],
    'object-src': ["'none'"],
    'base-uri': ["'none'"],
    'form-action': ["'none'"],
    'frame-ancestors': ["'none'"],
  };
}

export function buildCsp(scriptHashes = []) {
  return Object.entries(cspDirectives(scriptHashes))
    .map(([k, v]) => `${k} ${v.join(' ')}`)
    .join('; ');
}

/** frame-ancestors is ignored in a <meta> CSP, so the meta copy leaves it out (the header carries it). */
export function metaCsp(scriptHashes = []) {
  return buildCsp(scriptHashes).replace(/; frame-ancestors [^;]+/, '');
}

/** Every header except CSP, sent on every path. */
export const SECURITY_HEADERS = {
  'X-Content-Type-Options': 'nosniff',
  'X-Frame-Options': 'DENY',
  'Referrer-Policy': 'strict-origin-when-cross-origin',
  'Permissions-Policy': 'camera=(), microphone=(), geolocation=(), payment=(), usb=(), interest-cohort=()',
  'Strict-Transport-Security': 'max-age=63072000; includeSubDomains; preload',
  'Cross-Origin-Opener-Policy': 'same-origin',
  'Cross-Origin-Resource-Policy': 'same-origin',
};

/** Content-hashed build output can be cached forever; everything else revalidates. */
export const CACHE_RULES = [
  { path: '/_next/static/chunks/*', value: 'public, max-age=31536000, immutable' },
  { path: '/data/*', value: 'public, max-age=300' },
];

export const RENDER_BEGIN = '# BEGIN security headers (generated by scripts/render-headers.mjs; do not edit by hand)';
export const RENDER_END = '# END security headers';

/** The generated `headers:` entries for render.yaml, indented for a service under `services:`. */
export function renderHeaderBlock(scriptHashes, indent = '      ') {
  const entry = (path, name, value) => `${indent}- path: ${path}\n${indent}  name: ${name}\n${indent}  value: "${value}"`;
  const lines = [
    `${indent}${RENDER_BEGIN}`,
    entry('/*', 'Content-Security-Policy', buildCsp(scriptHashes)),
    ...Object.entries(SECURITY_HEADERS).map(([k, v]) => entry('/*', k, v)),
    ...CACHE_RULES.map((r) => entry(r.path, 'Cache-Control', r.value)),
    `${indent}${RENDER_END}`,
  ];
  return lines.join('\n');
}

/** Parses the generated header entries back out of render.yaml: [{ path, name, value }]. */
export function parseRenderHeaders(yamlText) {
  const out = [];
  const re = /-\s+path:\s*(\S+)\s*\n\s+name:\s*([\w-]+)\s*\n\s+value:\s*"([^"\n]*)"/g;
  for (const m of yamlText.matchAll(re)) out.push({ path: m[1], name: m[2], value: m[3] });
  return out;
}

/** Render-style path glob: `*` matches anything (including `/`) at the end or inside a segment. */
export function pathMatches(pattern, pathname) {
  const re = new RegExp(`^${pattern.split('*').map((s) => s.replace(/[.+?^${}()|[\]\\]/g, '\\$&')).join('.*')}$`);
  return re.test(pathname);
}

export function scriptHashesIn(csp) {
  const scriptSrc = csp.split(';').map((d) => d.trim()).find((d) => d.startsWith('script-src ')) ?? '';
  return scriptSrc.split(/\s+/).filter((t) => t.startsWith("'sha256-"));
}
